name: scrape-lowes

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i playwright
      - run: npx playwright install --with-deps chromium

      - run: node scrape.js

      # This action stages, commits (if changed), and pushes with the right token
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update prices"
          file_pattern: docs/lowes_prices.json
