name: scrape-lowes
on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i playwright
      - run: npx playwright install --with-deps chromium
      - run: node scrape.js
      - name: Commit results
        run: |
          git config user.name "price-bot"
          git config user.email "price-bot@example.com"
          mkdir -p docs
          git add docs/lowes_prices.json
          git commit -m "update prices" || echo "no changes"
          git push
